sonar.projectKey=Phoenix-Event-Ticketing_phoenix-online-user-service
sonar.organization=phoenix-event-ticketing
sonar.projectName=phoenix-online-user-service
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/coverage/**,**/node_modules/**,**/docs/**
